[package]
name = "brasa"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
crossterm = "0.28.1"
unicode-segmentation = "1.12.0"

[profile.release]
opt-level = 3
codegen-units = 1
panic = "abort"
strip = true
debug = false
